In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import torch
import ast

In [3]:
# parquet_path = "../data/raw/nng_15x15.parquet"
parquet_path = "../data/raw/nng_10x10.parquet"
df = pd.read_parquet(parquet_path)
pd.set_option('display.max_columns', None)   # show all columns
pd.set_option('display.max_rows',    None)   # show all rows (if you ever need it)
pd.set_option('display.width',        None)   # avoid line‑wraps
pd.set_option('display.max_colwidth', None)  # show full string values

df.head(1)

,puzzle_id,row_clues,col_clues,solution,intermediate_solutions,intermediate_methods,grid_density,grid_height,grid_width,steps,requires_search
0,0,"[[1, 1, 1], [2, 1, 1], [1, 2], [1, 5, 2], [2, 2], [2, 1, 1], [2, 2], [1, 1, 2], [1, 1, 1, 1, 1], [3, 5]]","[[1, 3, 1, 1], [1, 2, 1], [1, 1, 1, 2], [1, 1, 1, 1], [1, 1], [2, 1, 1], [3, 1, 2], [1, 1, 1, 1], [1, 5, 1], [1, 1, 1, 2]]","[[1, 0, 0, 0, 0, 0, 0, 1, 0, 1], [0, 0, 1, 1, 0, 0, 1, 0, 1, 0], [1, 0, 0, 0, 0, 1, 1, 0, 0, 0], [1, 0, 1, 1, 1, 1, 1, 0, 1, 1], [1, 1, 0, 0, 0, 0, 0, 1, 1, 0], [0, 0, 1, 1, 0, 0, 1, 0, 1, 0], [1, 1, 0, 0, 0, 0, 0, 0, 1, 1], [0, 1, 0, 0, 0, 1, 0, 1, 1, 0], [1, 0, 1, 0, 1, 0, 1, 0, 0, 1], [0, 1, 1, 1, 0, 1, 1, 1, 1, 1]]","[[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 1, 0, 0, 0], [1, 0, 1, 1, 1, 1, 1, 0, 1, 1], [1, 0, 0, 0, 0, 0, 0, 0, 1, 0], [0, 0, 0, 0, 0, 0, 0, 0, 1, 0], [0, 0, 0, 0, 0, 0, 0, 0, 1, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 1, 1, 0, 0, 1, 1, 1, 1, 0]], [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 1, 0, 0, 0], [1, 0, 1, 1, 1, 1, 1, 0, 1, 1], [1, 1, 0, 0, 0, 0, 0, 0, 1, 0], [0, 0, 0, 0, 0, 0, 0, 0, 1, 0], [0, 0, 0, 0, 0, 0, 0, 0, 1, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 1, 0, 0, 0, 1, 0, 0, 1], [0, 1, 1, 0, 0, 1, 1, 1, 1, 0]], [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 1, 0, 0, 0], [0, 0, 0, 0, 0, 0, 1, 0, 0, 0], [1, 0, 1, 1, 1, 1, 1, 0, 1, 1], [1, 1, 0, 0, 0, 0, 0, 1, 1, 0], [0, 0, 0, 0, 0, 0, 0, 0, 1, 0], [0, 0, 0, 0, 0, 0, 0, 0, 1, 1], [0, 0, 0, 0, 0, 0, 0, 0, 1, 0], [1, 0, 1, 0, 1, 0, 1, 0, 0, 1], [0, 1, 1, 0, 0, 1, 1, 1, 1, 1]], [[1, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 1, 0, 0, 0], [1, 0, 0, 0, 0, 0, 1, 0, 0, 0], [1, 0, 1, 1, 1, 1, 1, 0, 1, 1], [1, 1, 0, 0, 0, 0, 0, 1, 1, 0], [0, 0, 0, 0, 0, 0, 0, 0, 1, 0], [1, 0, 0, 0, 0, 0, 0, 0, 1, 1], [0, 0, 0, 0, 0, 0, 0, 1, 1, 0], [1, 0, 1, 0, 1, 0, 1, 0, 0, 1], [0, 1, 1, 0, 0, 1, 1, 1, 1, 1]], [[1, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 1, 0, 0, 0, 1, 0, 0, 0], [1, 0, 0, 0, 0, 1, 1, 0, 0, 0], [1, 0, 1, 1, 1, 1, 1, 0, 1, 1], [1, 1, 0, 0, 0, 0, 0, 1, 1, 0], [0, 0, 1, 0, 0, 0, 0, 0, 1, 0], [1, 1, 0, 0, 0, 0, 0, 0, 1, 1], [0, 0, 0, 0, 0, 0, 0, 1, 1, 0], [1, 0, 1, 0, 1, 0, 1, 0, 0, 1], [0, 1, 1, 1, 0, 1, 1, 1, 1, 1]], [[1, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 1, 0, 0, 0, 1, 0, 0, 0], [1, 0, 0, 0, 0, 1, 1, 0, 0, 0], [1, 0, 1, 1, 1, 1, 1, 0, 1, 1], [1, 1, 0, 0, 0, 0, 0, 1, 1, 0], [0, 0, 1, 0, 0, 0, 1, 0, 1, 0], [1, 1, 0, 0, 0, 0, 0, 0, 1, 1], [0, 1, 0, 0, 0, 0, 0, 1, 1, 0], [1, 0, 1, 0, 1, 0, 1, 0, 0, 1], [0, 1, 1, 1, 0, 1, 1, 1, 1, 1]], [[1, 0, 0, 0, 0, 0, 0, 1, 0, 0], [0, 0, 1, 1, 0, 0, 1, 0, 0, 0], [1, 0, 0, 0, 0, 1, 1, 0, 0, 0], [1, 0, 1, 1, 1, 1, 1, 0, 1, 1], [1, 1, 0, 0, 0, 0, 0, 1, 1, 0], [0, 0, 1, 1, 0, 0, 1, 0, 1, 0], [1, 1, 0, 0, 0, 0, 0, 0, 1, 1], [0, 1, 0, 0, 0, 0, 0, 1, 1, 0], [1, 0, 1, 0, 1, 0, 1, 0, 0, 1], [0, 1, 1, 1, 0, 1, 1, 1, 1, 1]], [[1, 0, 0, 0, 0, 0, 0, 1, 0, 0], [0, 0, 1, 1, 0, 0, 1, 0, 0, 0], [1, 0, 0, 0, 0, 1, 1, 0, 0, 0], [1, 0, 1, 1, 1, 1, 1, 0, 1, 1], [1, 1, 0, 0, 0, 0, 0, 1, 1, 0], [0, 0, 1, 1, 0, 0, 1, 0, 1, 0], [1, 1, 0, 0, 0, 0, 0, 0, 1, 1], [0, 1, 0, 0, 0, 1, 0, 1, 1, 0], [1, 0, 1, 0, 1, 0, 1, 0, 0, 1], [0, 1, 1, 1, 0, 1, 1, 1, 1, 1]], [[1, 0, 0, 0, 0, 0, 0, 1, 0, 1], [0, 0, 1, 1, 0, 0, 1, 0, 1, 0], [1, 0, 0, 0, 0, 1, 1, 0, 0, 0], [1, 0, 1, 1, 1, 1, 1, 0, 1, 1], [1, 1, 0, 0, 0, 0, 0, 1, 1, 0], [0, 0, 1, 1, 0, 0, 1, 0, 1, 0], [1, 1, 0, 0, 0, 0, 0, 0, 1, 1], [0, 1, 0, 0, 0, 1, 0, 1, 1, 0], [1, 0, 1, 0, 1, 0, 1, 0, 0, 1], [0, 1, 1, 1, 0, 1, 1, 1, 1, 1]], [[1, 0, 0, 0, 0, 0, 0, 1, 0, 1], [0, 0, 1, 1, 0, 0, 1, 0, 1, 0], [1, 0, 0, 0, 0, 1, 1, 0, 0, 0], [1, 0, 1, 1, 1, 1, 1, 0, 1, 1], [1, 1, 0, 0, 0, 0, 0, 1, 1, 0], [0, 0, 1, 1, 0, 0, 1, 0, 1, 0], [1, 1, 0, 0, 0, 0, 0, 0, 1, 1], [0, 1, 0, 0, 0, 1, 0, 1, 1, 0], [1, 0, 1, 0, 1, 0, 1, 0, 0, 1], [0, 1, 1, 1, 0, 1, 1, 1, 1, 1]]]","[cprop, cprop, cprop, cprop, cprop, cprop, cprop, cprop, cprop, cprop]",0.47,10,10,10,False

In [4]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
puzzle_id,100000.0,49999.500000,28867.657797,0.00,24999.75,49999.50,74999.25,99999.00
grid_density,100000.0,0.509601,0.049607,0.29,0.48,0.51,0.54,0.72
grid_height,100000.0,10.000000,0.000000,10.00,10.00,10.00,10.00,10.00
grid_width,100000.0,10.000000,0.000000,10.00,10.00,10.00,10.00,10.00
steps,100000.0,10.364570,9.005858,2.00,6.00,7.00,11.00,99.00

In [5]:
df["requires_search"].value_counts(normalize=True)

requires_search
False    0.79805
True     0.20195
Name: proportion, dtype: float64

In [6]:
def display_grid(ax, grid, clues=None, title=''):
    ax.imshow(grid.cpu().numpy(), cmap='gray_r', interpolation='nearest')
    ax.set_xlim(-0.5, grid.shape[1] - 0.5)
    ax.set_ylim(grid.shape[0] - 0.5, -0.5)
    for i in range(grid.shape[0] + 1):
        ax.axhline(i - 0.5, color='black', linewidth=1, clip_on=False)
    for j in range(grid.shape[1] + 1):
        ax.axvline(j - 0.5, color='black', linewidth=1, clip_on=False)
    ax.axis('off')
    if clues is not None:
        for i, row_clue in enumerate(clues[0]):
            clue_str = ",".join(str(int(num)) for num in row_clue if num > 0) or "0"
            ax.text(-0.6, i, clue_str, va='center', ha='right', fontsize=12)
        for j, col_clue in enumerate(clues[1]):
            clue_str = ",".join(str(int(num)) for num in col_clue if num > 0) or "0"
            ax.text(j, -0.6, clue_str, va='bottom', ha='center', fontsize=12)
    ax.set_title(title, fontsize=14)

In [7]:
def convert_string_data(data_string):
    parsed = ast.literal_eval(data_string)
    result = []
    for item in parsed:
        matrix_str, label = item
        matrix = ast.literal_eval(matrix_str)
        result.append([matrix, label])
    return result

In [8]:
for a in range(8):
    data = convert_string_data(df["intermediate_solutions"][a])
    grid_width = 4
    grid_height = (len(data) + grid_width - 1) // grid_width
    fig, axes = plt.subplots(
        grid_height,
        grid_width,
        figsize=(20, 5 * grid_height),
        squeeze=False,          # always returns a 2‑D ndarray
    )
    print(f"Row clues for solution {a}: {df['row_clues'][a]}")
    print(f"Column clues for solution {a}: {df['col_clues'][a]}")
    for i, (matrix, label) in enumerate(data[::-1]):
        row = i // grid_width
        col = i % grid_width
        display_grid(axes[row, col], torch.tensor(matrix), title=label)
    total_cells = grid_height * grid_width
    if len(data) < total_cells:
        for j in range(len(data), total_cells):
            row = j // grid_width
            col = j % grid_width
            axes[row, col].axis('off')

    plt.tight_layout()
    plt.show()

ValueError: malformed node or string: array([array([array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8),
              array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8),
              array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0], dtype=int8),
              array([1, 0, 1, 1, 1, 1, 1, 0, 1, 1], dtype=int8),
              array([1, 0, 0, 0, 0, 0, 0, 0, 1, 0], dtype=int8),
              array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0], dtype=int8),
              array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0], dtype=int8),
              array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8),
              array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8),
              array([0, 1, 1, 0, 0, 1, 1, 1, 1, 0], dtype=int8)], dtype=object),
       array([array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8),
              array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8),
              array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0], dtype=int8),
              array([1, 0, 1, 1, 1, 1, 1, 0, 1, 1], dtype=int8),
              array([1, 1, 0, 0, 0, 0, 0, 0, 1, 0], dtype=int8),
              array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0], dtype=int8),
              array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0], dtype=int8),
              array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8),
              array([0, 0, 1, 0, 0, 0, 1, 0, 0, 1], dtype=int8),
              array([0, 1, 1, 0, 0, 1, 1, 1, 1, 0], dtype=int8)], dtype=object),
       array([array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8),
              array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0], dtype=int8),
              array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0], dtype=int8),
              array([1, 0, 1, 1, 1, 1, 1, 0, 1, 1], dtype=int8),
              array([1, 1, 0, 0, 0, 0, 0, 1, 1, 0], dtype=int8),
              array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0], dtype=int8),
              array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1], dtype=int8),
              array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0], dtype=int8),
              array([1, 0, 1, 0, 1, 0, 1, 0, 0, 1], dtype=int8),
              array([0, 1, 1, 0, 0, 1, 1, 1, 1, 1], dtype=int8)], dtype=object),
       array([array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8),
              array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0], dtype=int8),
              array([1, 0, 0, 0, 0, 0, 1, 0, 0, 0], dtype=int8),
              array([1, 0, 1, 1, 1, 1, 1, 0, 1, 1], dtype=int8),
              array([1, 1, 0, 0, 0, 0, 0, 1, 1, 0], dtype=int8),
              array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0], dtype=int8),
              array([1, 0, 0, 0, 0, 0, 0, 0, 1, 1], dtype=int8),
              array([0, 0, 0, 0, 0, 0, 0, 1, 1, 0], dtype=int8),
              array([1, 0, 1, 0, 1, 0, 1, 0, 0, 1], dtype=int8),
              array([0, 1, 1, 0, 0, 1, 1, 1, 1, 1], dtype=int8)], dtype=object),
       array([array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8),
              array([0, 0, 1, 0, 0, 0, 1, 0, 0, 0], dtype=int8),
              array([1, 0, 0, 0, 0, 1, 1, 0, 0, 0], dtype=int8),
              array([1, 0, 1, 1, 1, 1, 1, 0, 1, 1], dtype=int8),
              array([1, 1, 0, 0, 0, 0, 0, 1, 1, 0], dtype=int8),
              array([0, 0, 1, 0, 0, 0, 0, 0, 1, 0], dtype=int8),
              array([1, 1, 0, 0, 0, 0, 0, 0, 1, 1], dtype=int8),
              array([0, 0, 0, 0, 0, 0, 0, 1, 1, 0], dtype=int8),
              array([1, 0, 1, 0, 1, 0, 1, 0, 0, 1], dtype=int8),
              array([0, 1, 1, 1, 0, 1, 1, 1, 1, 1], dtype=int8)], dtype=object),
       array([array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8),
              array([0, 0, 1, 0, 0, 0, 1, 0, 0, 0], dtype=int8),
              array([1, 0, 0, 0, 0, 1, 1, 0, 0, 0], dtype=int8),
              array([1, 0, 1, 1, 1, 1, 1, 0, 1, 1], dtype=int8),
              array([1, 1, 0, 0, 0, 0, 0, 1, 1, 0], dtype=int8),
              array([0, 0, 1, 0, 0, 0, 1, 0, 1, 0], dtype=int8),
              array([1, 1, 0, 0, 0, 0, 0, 0, 1, 1], dtype=int8),
              array([0, 1, 0, 0, 0, 0, 0, 1, 1, 0], dtype=int8),
              array([1, 0, 1, 0, 1, 0, 1, 0, 0, 1], dtype=int8),
              array([0, 1, 1, 1, 0, 1, 1, 1, 1, 1], dtype=int8)], dtype=object),
       array([array([1, 0, 0, 0, 0, 0, 0, 1, 0, 0], dtype=int8),
              array([0, 0, 1, 1, 0, 0, 1, 0, 0, 0], dtype=int8),
              array([1, 0, 0, 0, 0, 1, 1, 0, 0, 0], dtype=int8),
              array([1, 0, 1, 1, 1, 1, 1, 0, 1, 1], dtype=int8),
              array([1, 1, 0, 0, 0, 0, 0, 1, 1, 0], dtype=int8),
              array([0, 0, 1, 1, 0, 0, 1, 0, 1, 0], dtype=int8),
              array([1, 1, 0, 0, 0, 0, 0, 0, 1, 1], dtype=int8),
              array([0, 1, 0, 0, 0, 0, 0, 1, 1, 0], dtype=int8),
              array([1, 0, 1, 0, 1, 0, 1, 0, 0, 1], dtype=int8),
              array([0, 1, 1, 1, 0, 1, 1, 1, 1, 1], dtype=int8)], dtype=object),
       array([array([1, 0, 0, 0, 0, 0, 0, 1, 0, 0], dtype=int8),
              array([0, 0, 1, 1, 0, 0, 1, 0, 0, 0], dtype=int8),
              array([1, 0, 0, 0, 0, 1, 1, 0, 0, 0], dtype=int8),
              array([1, 0, 1, 1, 1, 1, 1, 0, 1, 1], dtype=int8),
              array([1, 1, 0, 0, 0, 0, 0, 1, 1, 0], dtype=int8),
              array([0, 0, 1, 1, 0, 0, 1, 0, 1, 0], dtype=int8),
              array([1, 1, 0, 0, 0, 0, 0, 0, 1, 1], dtype=int8),
              array([0, 1, 0, 0, 0, 1, 0, 1, 1, 0], dtype=int8),
              array([1, 0, 1, 0, 1, 0, 1, 0, 0, 1], dtype=int8),
              array([0, 1, 1, 1, 0, 1, 1, 1, 1, 1], dtype=int8)], dtype=object),
       array([array([1, 0, 0, 0, 0, 0, 0, 1, 0, 1], dtype=int8),
              array([0, 0, 1, 1, 0, 0, 1, 0, 1, 0], dtype=int8),
              array([1, 0, 0, 0, 0, 1, 1, 0, 0, 0], dtype=int8),
              array([1, 0, 1, 1, 1, 1, 1, 0, 1, 1], dtype=int8),
              array([1, 1, 0, 0, 0, 0, 0, 1, 1, 0], dtype=int8),
              array([0, 0, 1, 1, 0, 0, 1, 0, 1, 0], dtype=int8),
              array([1, 1, 0, 0, 0, 0, 0, 0, 1, 1], dtype=int8),
              array([0, 1, 0, 0, 0, 1, 0, 1, 1, 0], dtype=int8),
              array([1, 0, 1, 0, 1, 0, 1, 0, 0, 1], dtype=int8),
              array([0, 1, 1, 1, 0, 1, 1, 1, 1, 1], dtype=int8)], dtype=object),
       array([array([1, 0, 0, 0, 0, 0, 0, 1, 0, 1], dtype=int8),
              array([0, 0, 1, 1, 0, 0, 1, 0, 1, 0], dtype=int8),
              array([1, 0, 0, 0, 0, 1, 1, 0, 0, 0], dtype=int8),
              array([1, 0, 1, 1, 1, 1, 1, 0, 1, 1], dtype=int8),
              array([1, 1, 0, 0, 0, 0, 0, 1, 1, 0], dtype=int8),
              array([0, 0, 1, 1, 0, 0, 1, 0, 1, 0], dtype=int8),
              array([1, 1, 0, 0, 0, 0, 0, 0, 1, 1], dtype=int8),
              array([0, 1, 0, 0, 0, 1, 0, 1, 1, 0], dtype=int8),
              array([1, 0, 1, 0, 1, 0, 1, 0, 0, 1], dtype=int8),
              array([0, 1, 1, 1, 0, 1, 1, 1, 1, 1], dtype=int8)], dtype=object)],
      dtype=object)

In [9]:
import numpy as np
data1 = np.load("../data/processed/nonogram_easy_X.npy")

In [10]:
print(data1[0])
print(data1.shape)

[[[2. 1. 0.]
  [1. 0. 0.]
  [1. 1. 1.]
  [2. 0. 0.]
  [1. 1. 0.]]

 [[1. 1. 0.]
  [1. 0. 0.]
  [1. 1. 0.]
  [1. 1. 0.]
  [4. 0. 0.]]]
(9982, 2, 5, 3)

In [11]:
import numpy as np
from itertools import zip_longest

def pad_nested_lists(data, max_len=3):
    padded = [
        [inner + [0] * (max_len - len(inner)) for inner in outer]
        for outer in data
    ]
    return np.array(padded, dtype=float)

# Alternative using numpy.pad
def pad_nested_lists_np(data, max_len=3):
    """
    Pad inner lists with zeros using numpy operations.
    """
    # Convert to object array first to handle variable lengths
    result = []
    for outer in data:
        padded_outer = []
        for inner in outer:
            arr = np.array(inner, dtype=float)
            if len(arr) < max_len:
                arr = np.pad(arr, (0, max_len - len(arr)), mode='constant')
            padded_outer.append(arr)
        result.append(np.stack(padded_outer))
    
    return np.stack(result)

# Usage
inputs = [[[3], [1, 1, 1], [1, 1], [1], [1]], [[2], [1], [2, 2], [1], [2]]]

print("Method 1 (list comprehension):")
output1 = pad_nested_lists(inputs, max_len=3)
print(output1)

print("\nMethod 2 (numpy.pad):")
output2 = pad_nested_lists_np(inputs, max_len=3)
print(output2)

Method 1 (list comprehension):
[[[3. 0. 0.]
  [1. 1. 1.]
  [1. 1. 0.]
  [1. 0. 0.]
  [1. 0. 0.]]

 [[2. 0. 0.]
  [1. 0. 0.]
  [2. 2. 0.]
  [1. 0. 0.]
  [2. 0. 0.]]]

Method 2 (numpy.pad):
[[[3. 0. 0.]
  [1. 1. 1.]
  [1. 1. 0.]
  [1. 0. 0.]
  [1. 0. 0.]]

 [[2. 0. 0.]
  [1. 0. 0.]
  [2. 2. 0.]
  [1. 0. 0.]
  [2. 0. 0.]]]

In [12]:
from compactreasoningmodels.datasets.nonogram_dataset import NonogramDataset

ds = NonogramDataset(parquet_path)